image: node:latest

stages:
  - build
  - prod

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install

production:
  stage: prod
  script: pm2 start ecosystem.config.js
