image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install

testing_test:
  stage: test
  script: yarn test
