image: node:latest

stages:
  - build
  - test
  - prod

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install

testing:
  stage: test
  script: yarn test

production:
  stage: prod
  script: pm2 start ecosystem.config.js
