image: node:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "loft_server"
  MYSQL_ROOT_PASSWORD: "THEviper22"

stages:
  - build
  - test
  - prod

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn install

testing:
  stage: test
  script: yarn test

production:
  stage: prod
  script: pm2 start ecosystem.config.js
